#!groovy

currentBuild.result = "SUCCESS"
pipeline {
    agent {
	 label "CN-OMNI-Automation"
	}
	 parameters {
        string(name: 'Env', defaultValue: 'staging', description: 'the environment for test running')
    }
	stages{
        stage("${params.Env} Testing start ") {
            steps {
              sh "behave -D env=${params.Env} --junit '/UI automation/OMNI_UI_automation/reports/'"
            }
			}
			
			}
            post {
                always {
                    junit 'UI automation/OMNI_UI_automation/reports/*.xml'
                }
			 failure {
                 mail to: 'sunny.yu2@ef.com',
                 subject: "[Jenkins Notification] ${PROJECT_NAME} - Run # ${BUILD_NUMBER}
                  Results(${TEST_COUNTS,var="pass"}/${TEST_COUNTS,var="total"}) - ${BUILD_STATUS}'",
                 body: "<html>
<head>
<meta charset="UTF-8">
<title>${ENV, var="JOB_NAME"}-The ${BUILD_NUMBER}th Build Log</title>
</head>
<body leftmargin="8" marginwidth="0" topmargin="8" marginheight="4"
    offset="0">
    <table width="95%" cellpadding="0" cellspacing="0"
        style="font-size: 11pt; font-family: Tahoma, Arial, Helvetica, sans-serif">
        
        <tr>
            <td><h2>
                    <font color="#FF00FF">Build Result - ${BUILD_STATUS}</font>
                </h2></td>
        </tr>
        <tr>
            <td><br />
            <b><font color="#EE82EE">Build Detail Information:</font></b>
            <hr size="2" width="100%" align="center" /></td>
        </tr>
        <tr>
            <td>
                <ul>
                    <li>Project Name&nbsp;：&nbsp;${PROJECT_NAME}</li>
                    <li>Build Number&nbsp;：&nbsp; The ${BUILD_NUMBER}th build</li>
                    <li>Build Cause：&nbsp;${CAUSE}</li>
                    <li>Build Log：&nbsp;<a href="${BUILD_URL}console">${BUILD_URL}console</a></li>
                    <li>Build&nbsp;&nbsp;Url&nbsp;：&nbsp;<a href="${BUILD_URL}">${BUILD_URL}</a></li>                  
                    <li>Pass Rate&nbsp;：&nbsp; ${TEST_COUNTS,var="pass"}/${TEST_COUNTS, var="total"}</li>
                </ul>
            </td>
        </tr>
        
        <tr>
            <td><b><font color="#EE82EE">Failed Test Results</font></b>
            <hr size="2" width="100%" align="center" /></td>
        </tr>
        <tr>
            <td><pre
                    style="font-size: 11pt; font-family: Tahoma, Arial, Helvetica, sans-serif">$FAILED_TESTS</pre>
                <br /></td>
        </tr>
        <tr>
            <td><b><font color="#EE82EE">Changes Since Last
                        Successful Build:</font></b>
            <hr size="2" width="100%" align="center" /></td>
        </tr>
        <tr>
            <td>
                <ul>
                    <li>Changes of History: <a href="${PROJECT_URL}changes">${PROJECT_URL}changes</a></li>
                </ul> ${CHANGES_SINCE_LAST_SUCCESS,reverse=true, format="Changes for Build #%n:<br />%c<br />",showPaths=true,changesFormat="<pre>[%a]<br />%m</pre>",pathFormat="&nbsp;&nbsp;&nbsp;&nbsp;%p"}
            </td>
        </tr>
        <tr>
            <td><b><font color="#EE82EE">Build Log:</font></b>
            <hr size="2" width="100%" align="center" /></td>
        </tr>
        <tr>
            <td><textarea cols="80" rows="30" readonly="readonly"
                    style="font-family: Courier New">${BUILD_LOG}</textarea>
            </td>
        </tr>
        <tr>
            <td><font color="#FF00FF">The mail is automatically distributed, please do not reply.</font></td>
        </tr>
    </table>
</body>
</html>'''"

        }	
            }
        }
       









