version: '3.4'

services:
  app:
    build: .
    volumes:
      - .:/opt/app
      - yarn-cache:/opt/.yarn-cache
    ports:
      - '8080:8080'
    environment:
      PORT: '8080'

  dynamodb:
    image: deangiberson/aws-dynamodb-local

volumes:
  yarn-cache:
